---
#Here you can change the messages that will display
#Use "§" as a color symbol
#Use "\n" to go to the next line
#The title of the menu
Title: "§cSP§dTM §7Staff"
#The content of the menu (Description)
Content: "§4Owners: §7MarioTM04 | KenoZeu \n §aAdmin: §7xRaulGaming180x \n §bMod: §7qKoppe \n §2Helper: §7EdyGamerRo"
#Returns button name
Button: "§6I understand,Staff da best."
...
